OnlineCreditsTeam1/OnlineCreditsTeam1/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using OnlineCreditsTeam1.Data;
using OnlineCreditsTeam1.Models;
using OnlineCreditsTeam1.Models.ManageViewModels;
using OnlineCreditsTeam1.Services;
using X.PagedList;

namespace OnlineCreditsTeam1.Controllers
{
    [Authorize]
    public class UserManagementController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IEmailSender _emailSender;
        private readonly ILogger _logger;
        private PasswordGenerator _passwordGenerator;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private const int pageSize = 4;
        private readonly FileUploadService _fileUploadService;
        private readonly IHostingEnvironment _environment;
        private readonly IStringLocalizer<UserManagementController> _localizer;
        private JsonService _jsonService;

        public UserManagementController(
            PasswordGenerator passwordGenerator,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IEmailSender emailSender,
            ILogger<AccountController> logger,
            RoleManager<IdentityRole> roleManager,
            ApplicationDbContext context,
            FileUploadService fileUploadService,
            IHostingEnvironment environment,
            IStringLocalizer<UserManagementController> localizer,
            JsonService jsonService
            )
        {
            _userManager = userManager;
            _passwordGenerator = passwordGenerator;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _logger = logger;
            _roleManager = roleManager;
            _context = context;
            _fileUploadService = fileUploadService;
            _environment = environment;
            _localizer = localizer;
            _jsonService = jsonService;
        }


        public enum SortState
        {
            NameAsc,
            NameDesc,
            DateAsc,
            DateDesc,
            UserNameAsc,
            UserNameDesc,
            StatusAsc,
            StatusDesc,
            RoleAsc,
            RoleDesc
        }

        // GET: UserManagement
        public async Task<IActionResult> UserListForAdmin(string userName, SortState sortOrder = SortState.NameAsc, int page = 1)
        {

            ViewBag.UserNameFilter = userName;
            var users = _context.Users.Where(u=> u.UserName !=null);

            ViewBag.CurrentSort = sortOrder;
            if (!string.IsNullOrWhiteSpace(userName))
            {
                users = users.Where(u => u.UserName.Contains(userName)||u.Name.Contains(userName));
            }

            
            ViewBag.NameSort = sortOrder == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
            ViewBag.DateSort = sortOrder == SortState.DateAsc ? SortState.DateDesc : SortState.DateAsc;
            ViewBag.UserNameSort = sortOrder == SortState.UserNameAsc ? SortState.UserNameDesc : SortState.UserNameAsc;
            ViewBag.RoleSort = sortOrder == SortState.RoleAsc ? SortState.RoleDesc : SortState.RoleAsc;
            ViewBag.StatusSort = sortOrder == SortState.StatusAsc ? SortState.StatusDesc : SortState.StatusAsc;

            switch (sortOrder)
            {
                case SortState.NameDesc:
                    users = users.OrderByDescending(s => s.Name);
                    break;
                case SortState.DateAsc:
                    users = users.OrderBy(s => s.CreateTime);
                    break;
                case SortState.DateDesc:
                    users = users.OrderByDescending(s => s.CreateTime);
                    break;
                case SortState.UserNameAsc:
                    users = users.OrderBy(s => s.UserName);
                    break;
                case SortState.UserNameDesc:
                    users = users.OrderByDescending(s => s.UserName);
                    break;
                case SortState.StatusAsc:
                    users = users.OrderBy(s => s.Status);
                    break;
                case SortState.StatusDesc:
                    users = users.OrderByDescending(s => s.Status);
                    break;
                case SortState.RoleAsc:
                    users = users.OrderBy(s => s.Role);
                    break;
                case SortState.RoleDesc:
                    users = users.OrderByDescending(s => s.Role);
                    break;
                default:
                    users = users.OrderBy(s => s.Name);
                    break;
            }


            IPagedList<ApplicationUser> usersForPages = users.ToPagedList(page, pageSize);
            return View(usersForPages);
        }

        public async Task<IActionResult> GetUsersByShopId(string shopId)
        {
            List<Order> orders = new List<Order>();
            try
            {
                orders = await _context.Order.Where(o => o.CorpClientId == shopId).ToListAsync();
            }
            catch (Exception e)
            {
                return PartialView("UsersPartial");
            }
            
            List<ApplicationUser> users = new List<ApplicationUser>();
            foreach (var order in orders)
            {
               users.Add(_userManager.Users.FirstOrDefault(u => u.Id == order.ClientId)); 
            }
            return PartialView("UsersPartial", users);
        }

        [HttpGet]
        public async Task<IActionResult> GetOrdersByShopId(string shopId)
        {
            SettingsService settingsService = new SettingsService();
            Order myOrder = new Order
            {
                BeginDate = DateTime.Now,
                FinishDate = DateTime.MaxValue,
                Id = 0,
                ClientId = "test_Client_Id",
                Sum = 0,
                Status = "Test",
                CorpClientId = "test_Corporative_Id"
            };
            List<Order> orders = new List<Order>();
            try
            {
                orders = await _context.Order.Where(o => o.CorpClientId == shopId).ToListAsync();
                List<Order> newOrders = await orders.Where(o => o.Status == "new").ToListAsync();
                if (newOrders.Count > 0)
                {
                    foreach (Order order in newOrders)
                    {
                        var documents = await _context.Documents.Where(o => o.OrderId == order.Id).ToListAsync();
                        if (documents.Count < 4 &&
                            DateTime.Now >= order.BeginDate.AddDays(settingsService.GetSettnigs().AutoCancelOrder))
                        {
                            order.Status = "Отклонена";
                            _context.Update(order);
                        }
                    }
                    await _context.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                orders.Add(myOrder);
            }

            return PartialView("_OrdersPartial", orders);
        }

        [HttpGet]
        public async Task<IActionResult> GetOrdersById(string userId)
        {
            SettingsService settingsService = new SettingsService();
            Order myOrder = new Order
            {
                BeginDate = DateTime.Now,
                FinishDate = DateTime.MaxValue,
                Id = 0,
                ClientId = "test_Client_Id",
                Sum = 0,
                Status = "Test",
                CorpClientId = "test_Corporative_Id"
            };
            List<Order> orders = new List<Order>();
            try
            {
                orders = await _context.Order.Where(o => o.ClientId == userId).ToListAsync();
                List<Order> newOrders = await orders.Where(o => o.Status == "new").ToListAsync();
                if (newOrders.Count > 0)
                {
                    foreach (Order order in newOrders)
                    {
                        var documents = await _context.Documents.Where(o => o.OrderId == order.Id).ToListAsync();
                        if (documents.Count < 4 &&
                            DateTime.Now >= order.BeginDate.AddDays(settingsService.GetSettnigs().AutoCancelOrder))
                        {
                            order.Status = "Отклонена";
                            _context.Update(order);
                        }
                    }
                    await _context.SaveChangesAsync();
                }
            }
            catch (Exception e)
            {
                orders.Add(myOrder);
            }
            
            
           // var applicationDbContext = _context.Order.Include(a => a.ClientId).Include(a => a.BeginDate).OrderByDescending(p => p.Status).ToList();
            return PartialView("_OrdersPartial", orders);
        }

        [HttpGet]
        public async Task<IActionResult> GetOrders()
        {
            SettingsService settingsService = new SettingsService();
            Order myOrder = new Order
            {
                BeginDate = DateTime.Now,
                FinishDate = DateTime.MaxValue,
                Id = 0,
                ClientId = "test_Client_Id",
                Sum = 0,
                Status = "Test",

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/UserManagement/GetReportForm.cshtml
@model GetReportModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div style="border: 1px solid silver; padding: 10px; border-radius: 5px;">
            <form method="get" asp-controller="Report" asp-action="GetReport">
                <h4 class="text-center">@Localizer["select_report_generation_options"]</h4>
                <div style="margin-top: 10px;">
                    <b class="form-label">@Localizer["date_since"]</b>
                    <input asp-for="BeginDate" placeholder="@Localizer["enter_the_start_date"]" class="form-control" type="date" />
                </div>
                <div style="margin-top: 10px;">
                    <b class="form-label">@Localizer["date_to"]</b>
                    <input asp-for="FinishDate" placeholder="@Localizer["enter_end_date"]" class="form-control" type="date" />
                </div>
                <h5 class="text-center" style="margin: 10px;">@Localizer["select_information "]</h5>
                <div style="margin: 10px 0; padding: 0 10px;">
                    <label for="declined_orders"><input asp-for="DeclinedOrders" id="declined_orders" placeholder="" type="checkbox" /> @Localizer["rejected_applications"]</label>
                </div>
                <div style="margin: 10px 0; padding: 0 10px;">
                    <label for="confirmed_orders"><input asp-for="ConfirmedOrders" id="confirmed_orders" placeholder="" type="checkbox" />@Localizer["approved_applications"]</label>
                </div>
                <input type="hidden" value="@Model.UserId" asp-for="UserId" />
                <div style="margin-top: 10px; padding: 0 10px;">
                    <label for="sell_dynamic"><input id="sell_dynamic" placeholder="" type="checkbox" />@Localizer["dynamics_of_sales"]</label>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-default">
                        @Localizer["get_the_report"]
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-3"></div>
</div>
<style>
    .form-label {
        margin-bottom: 5px;
        margin-left: 5px;
        display: block;
        font-weight: bold;
    }

    label:hover {
        cursor: pointer;
    }

    label {
        display: block;
        padding-left: 15px;
        text-indent: -15px;
    }

    input {
        width: 13px;
        height: 13px;
        padding: 0;
        margin: 0;
        vertical-align: bottom;
        position: relative;
        top: -1px;
        *overflow: hidden;
    }
</style>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/UserManagement/UserDetails.cshtml
@model OnlineCreditsTeam1.Models.ManageViewModels.UserProfileViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer



<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<div id="menuTabs">
    <ul class="buttons navContainer">
        <li><a class="btn tab-pane myBtn tab_btn" href="#UserInfo"><img style="margin-right: 5px;" src="~/StaticData/Anonymous/manual.png" />@Localizer["user_info"]</a></li>
        <li><a class="btn tab-pane myBtn tab_btn" id="orders" href="#Orders"><img style="margin-right: 5px;" src="~/StaticData/Anonymous/recommendation.png" />@Localizer["orders"]</a></li>
        <li><a class="btn tab-pane myBtn tab_btn" href="#Credits"><img style="margin-right: 5px;" src="~/StaticData/Anonymous/suitcase.png" /> @Localizer["credits"]</a></li>
        <li><a class="btn tab-pane myBtn tab_btn" href="#History"><img style="margin-right: 5px;" src="~/StaticData/Anonymous/calendar.png" /> @Localizer["story"]</a></li>
        @if (User.IsInRole("admin") || User.IsInRole("BankOperator"))
        {
            <li><a class="btn tab-pane myBtn tab_btn" id="reports" href="#User_Reports"><img style="margin-right: 5px;" src="~/StaticData/Anonymous/report.png" /> Отчеты</a></li>
        }
    </ul>
    <div class="tabs">
        <div id="Orders" class="col-md-12 ">
            <h2>@Localizer["orders"]</h2>
            <div class="loader"></div>
        </div>

        <div id="Credits" class="col-md-12">
            <h2>@Localizer["credits"]</h2>
            <div class="loader"></div>
        </div>
        <div id="User_Reports">
            <h3 class="text-center">Сформировать отчет</h3>
            @Html.Partial("GetReportForm", ViewData["GetReportModel"])
        </div>
        <div id="History" class="col-md-12">
            <table class="table">
                <tr style="padding-bottom: 5px; border-bottom: 1px solid silver;">
                    <th style="width: 80%;">@Localizer["action"]</th>
                    <th style="width: 20%; border-left: 1px solid silver;">@Localizer["date"]</th>
                </tr>

            </table>
        </div>
        <div id="UserInfo" class="col-md-12">
            @if (User.IsInRole("admin"))
            {
                if (Model.Status == "Активен")
                {
                    <form method="post" asp-action="Locked" asp-controller="Roles" style="position: absolute; bottom: 22%; left: 5%; z-index: 10;">
                        <input type="hidden" name="userId" value="@Model.Id" />
                        <button class="btn btn-default" type="submit">@Localizer["block"]</button>
                        <a class="btn btn-default" asp-action="Edit" asp-route-userId="@Model.Id" asp-controller="Roles">@Localizer["role"]</a>

                    </form>
                }
                else
                {
                    <form method="post" asp-action="UnLocked" asp-controller="Roles" style="position: absolute; bottom: 22%; left: 2%; z-index: 10;">
                        <input type="hidden" name="userId" value="@Model.Id" />
                        <button class="btn btn-default" type="submit">@Localizer["unlock"]</button>
                        <a class="btn btn-default" asp-action="Edit" asp-route-userId="@Model.Id" asp-controller="Roles">@Localizer["role"]</a>

                    </form>
                }
            }


            <form id="profile-form" method="post" enctype="multipart/form-data" class="col-md-12">
                @Html.Partial("_StatusMessage", ViewData["StatusMessage"])
                <div asp-validation-summary="All" class="text-danger"></div>
                <div style="display: inline-block; max-width: 200px; float: left; margin-right: 15px;">
                    <div>
                        <img class="card-img-top" src="@Model.PhotoPath" style="width: 200px; height: 200px;" alt="User's profile image">
                    </div>

                </div>

                <div>
                    <div class="form-group custom_input_fields" style="display: block; width: 70%; float: right">
                        <p><b class="custom_label">@Localizer["name"] :</b> <input  asp-for="@Model.Name" value="@Model.Name" /><br /></p>
                        <p><b class="custom_label">@Localizer["phone_number"] :</b> <input asp-for="@Model.UserName" value="@Model.UserName" /><br /></p>
                        <p><b class="custom_label">@Localizer["email"] :</b> <input asp-for="@Model.Email" value="@Model.Email" /><br /></p>   
                        <p><b class="custom_label">@Localizer["registration_date"] :</b> @Model.CreateDate.ToShortDateString()</p>
                        @if (Model.Role == "MarketOperator")
                        {
                            <p><b class="custom_label">@Localizer["bik"]:</b> <input asp-for="@Model.Requisits.Bik" value="@Model.Requisits.Bik" /><br /></p>
                            <p><b class="custom_label">@Localizer["bank_details"]:</b> <input asp-for="@Model.Requisits.BankAccountNumber" value="@Model.Requisits.BankAccountNumber" /><br /></p>
                            <p><b class="custom_label">@Localizer["legal_address"]:</b> <input asp-for="@Model.Requisits.LegalAdress" value="@Model.Requisits.LegalAdress" /><br /></p>
                        }
                        @if (Model.Role == "BankOperator" || Model.Role == "admin")
                        {
                            <p><b class="custom_label">@Localizer["inn"]:</b> <input asp-for="@Model.Requisits.Inn" value="@Model.Requisits.Inn" /><br /></p>
                        }
                        @if (Model.Role == "user")
                        {
                            <p><b class="custom_label">@Localizer["requisites"]:</b></p>
                        }
                        <input type="hidden" id="userId" value="@Model.Id" />
                        <div class="form-group" style="overflow: hidden;">
                            <p>@Localizer["edit_photo"]</p>
                            <input asp-for="PhotoFile" class="form-control" style="float: left; width: 40%; border: none; box-shadow: none; border-bottom: 1px solid silver;" />

                            <div asp-validation-summary="All" class="text-danger"></div>
                        </div>
                        <br />
                        <div>
                            <button type="submit" class="btn btn-default"> @Localizer["save"]</button>
                        </div>

                    </div>

                </div>

            </form>

            <a id="logs" type="button" class="btn btn-default">Show User logs</a>

            <div id="modalLogs" style="display: none; background: rgba(0, 0, 0, 0.5); z-index: 999; position: fixed; top: 0px; left: 0px; width: 100%; height: 100%;">
                <div style="position: absolute; top: 15%; left: 6%; width: 90%; border: 1px solid silver; padding: 10px; z-index: 99999; background: white;">
                    <h3>Текущее время : @DateTime.Now.Hour:@DateTime.Now.Minute <a id="btn_close" class="btn btn-default" type="button">Закрыть</a></h3>
                    <div id="logWindow" style="background: white;">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Tabs initialisation-->
<script>
    $("#menuTabs").tabs();
</script>

<!--Tabs custom actions-->
<script>
    $(".tab_btn").click(
        function () {
            window.location = this.href;
        });
    window.addEventListener('hashchange', function () {
        var x = `[href="${window.location.hash}"]`;
        $(x)[0].click();
    });
    $("#logs").on('click',
        function () {
            $.ajax({
                type: 'GET',
                data: {userId: $('#userId').val()},
                success: $('#logWindow').load('@Url.Action("GetLogsByUserId", "Orders")?userId=' + $('#userId').val())
            });
        });
    $("#logs").on('click',
        function () {
            $("#modalLogs").show();
        });
    $("#btn_close").on('click',
        function () {
            $("#modalLogs").hide();
        });
    $("#orders").on('click',
        function () {
            $.ajax({
                type: 'GET',
                data: {userId: $('#userId').val()},
                success: $('#Orders').load('@Url.Action("GetOrdersById", "UserManagement")?userId=' + $('#userId').val())
            });
        });

</script>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/UserManagement/UserListForAdmin.cshtml
@using System.Collections
@using X.PagedList
@using X.PagedList.Mvc.Common
@using X.PagedList.Mvc.Core
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model X.PagedList.IPagedList<ApplicationUser>
@inject RoleManager<IdentityRole> roleManager
@inject UserManager<ApplicationUser> UserManager

<form action="" method="get" class="search">
    <input type="search" name="userName" placeholder="поиск" value="@ViewBag.UserNameFilter" class="input" />
    <input type="hidden" name="sortOrder" value="@ViewBag.CurrentSort " />
    <input type="submit" name="" value="" class="submit" />
</form>



<table class="table table-striped">
    <thead>
        <tr>

            <th scope="col">
                <a asp-action="UserListForAdmin"
                   asp-route-userName="@ViewBag.UserNameFilter"
                   asp-route-sortOrder="@ViewBag.NameSort">
                    @Localizer["name"]
                </a>
            </th>
            <th scope="col">
                <a asp-action="UserListForAdmin"
                   asp-route-userName="@ViewBag.UserNameFilter"
                   asp-route-sortOrder="@ViewBag.RoleSort">
                    @Localizer["role"]
                </a>
            </th>
            <th scope="col">
                <a asp-action="UserListForAdmin"
                   asp-route-userName="@ViewBag.UserNameFilter"
                   asp-route-sortOrder="@ViewBag.UserNameSort">
                    @Localizer["phone_number"]
                </a>
            </th>
            <th scope="col">
                <a asp-action="UserListForAdmin"
                   asp-route-userName="@ViewBag.UserNameFilter"
                   asp-route-sortOrder="@ViewBag.StatusSort">
                    @Localizer["status"]
                </a>
            </th>

            <th scope="col">
                <a asp-action="UserListForAdmin"
                   asp-route-userName="@ViewBag.UserNameFilter"
                   asp-route-sortOrder="@ViewBag.DateSort">
                    @Localizer["registration_date"]
                </a>
            </th>
            <th scope="col">@Localizer["datails"]</th>
            <th scope="col">@Localizer["limits"]</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Name</td>
                <td>@user.Role</td>
                <td>@user.UserName</td>
                <td>@user.Status</td>
                <td>@user.CreateTime</td>
                <td><a asp-action="UserDetails" asp-route-id="@user.Id" class="button xbox">Profile</a></td>
                <td><a asp-route-id="@user.Id" class="button xbox">Limits</a></td>

            </tr>
        }


    </tbody>
</table>



<div>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount

    @if (Model.HasPreviousPage)
    {
        @Html.ActionLink("<<", "UserListForAdmin", new { page = 1, sortOrder = ViewBag.CurrentSort, userName = ViewBag.UserNameFilter })
        @Html.Raw(" ");
        @Html.ActionLink("< Prev", "UserListForAdmin", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, userName = ViewBag.UserNameFilter })
    }
    else
    {
        @:<<
        @Html.Raw(" ");
        @:< Prev
    }

    @if (Model.HasNextPage)
    {
        @Html.ActionLink("Next >", "UserListForAdmin", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, userName = ViewBag.UserNameFilter })
        @Html.Raw(" ");
        @Html.ActionLink(">>", "UserListForAdmin", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, userName = ViewBag.UserNameFilter })
    }
    else
    {
        @:Next >
        @Html.Raw(" ")
        @:>>
    }
</div>

<style>
    a.button.xbox {
        background: #c4e125;
        background: -webkit-gradient(linear, 0 0, 0 bottom, from(#c4e125), to(#88a819));
        background: -moz-linear-gradient(#c4e125, #88a819);
        background: linear-gradient(#c4e125, #88a819);
        border: solid 1px #829c15;
        border-bottom: solid 3px #819d15;
        box-shadow: inset 0 0 0 1px #c6da7b;
        color: #fff;
        text-shadow: 0 1px 0 #819d15;
    }

        a.button.xbox:hover {
            background: #88a819;
            background: -webkit-gradient(linear, 0 0, 0 bottom, from(#88a819), to(#c4e125));
            background: -moz-linear-gradient(#88a819, #c4e125);
            background: linear-gradient(#88a819, #c4e125);
            border: solid 1px #829c15;
            border-bottom: solid 3px #819d15;
            box-shadow: inset 0 0 0 1px #c6da7b;
        }

        a.button.xbox:active {
            background: #88a819;
            background: -webkit-gradient(linear, 0 0, 0 bottom, from(#88a819), to(#c4e125));
            background: -moz-linear-gradient(#88a819, #c4e125);
            background: linear-gradient(#88a819, #c4e125);
            border: solid 1px #829c15;
            box-shadow: inset 0 10px 15px 0 #819d15;
        }


    .search {
        width: 20%;
        position: relative;
        margin-top: 20px;
    }

        .search input {
            border: none;
        }

        .search .input {
            width: 100%;
            padding: 8px 37px 9px 15px;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            box-shadow: inset 0 0 5px rgba(0,0,0,0.1), inset 0 1px 2px rgba(0,0,0,0.3);
            border-radius: 20px;
            background: #EEE;
            font: 13px Tahoma, Arial, sans-serif;
            color: #555;
            outline: none;
        }

            .search .input:focus {
                box-shadow: inset 0 0 5px rgba(0,0,0,0.2), inset 0 1px 2px rgba(0,0,0,0.4);
                background: #E8E8E8;
                color: #333;
            }

        .search .submit {
            position: absolute;
            top: 0;
            right: 0;
            width: 37px;
            height: 100%;
            cursor: pointer;
            background: url(https://lh4.googleusercontent.com/-b-5aBxcxarY/UAfFW9lVyjI/AAAAAAAABUg/gQtEXuPuIds/s13/go.png) 50% no-repeat;
            opacity: 0.5;
        }

            .search .submit:hover {
                opacity: 0.8;
            }

    input[type="search"] {
        -webkit-appearance: none;
    }
</style>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/UserManagement/UsersPartial.cshtml
@model List<ApplicationUser>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<div id="searchresults">

    @if (Model.Count == 0)
    {
    <h4 class="text-center">@Localizer["there_are_no_users_to_display"]</h4>
    }
    @if (Model.Count > 0)
    {

        <div style="font-weight: bold;">
            <span style="width: 30%; display: inline-block;">@Localizer["name"]</span>
            <span style="width: 19%;  display: inline-block; text-align: center;">@Localizer["registration_date"]</span>
            <span style="width: 19%;  display: inline-block;">@Localizer["phone_number"]</span>
            <span style="width: 18%;  display: inline-block;">@Localizer["email"]</span>
            <span style="width: 10%;  display: inline-block;">@Localizer["status"]</span>
        </div>

        foreach (ApplicationUser user in Model)
        {

        <a class="btnHover" asp-action="UserDetails" asp-route-id="@user.Id" style="display: block; padding: 10px 0 5px; color: black; text-decoration: none; border-bottom: 1px solid silver;">
            <span style="width: 30%; display: inline-block;">@user.Name</span>
            <span style="width: 19%;  display: inline-block; text-align: center;">@user.CreateTime.ToShortDateString()</span>
            <span style="width: 19%;  display: inline-block;">@user.PhoneNumber</span>
            <span style="width: 18%;  display: inline-block;">@user.Email</span>
            <span style="width: 10%;  display: inline-block;">@user.Status</span>
        </a>

        }
    }

</div>

<style>
    #searchresults a.btnHover:hover {
        background: rgba(9, 30, 66, 0.04) !important;
    }
</style>