OnlineCreditsTeam1/OnlineCreditsTeam1/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineCreditsTeam1.Models
{
    public class Payment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Term { get; set; }
        public IEnumerable<Provider> Providers { get; set; }
    }
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineCreditsTeam1.Data;
using OnlineCreditsTeam1.Models;

namespace OnlineCreditsTeam1.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PaymentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            return PartialView(await _context.Payments.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .SingleOrDefaultAsync(m => m.Id == id);
            if (payment == null)
            {
                return NotFound();
            }

            return PartialView(payment);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Term")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return RedirectToAction("AdminProfile", "Manage", "_Payments");
            }
            return PartialView(payment);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments.SingleOrDefaultAsync(m => m.Id == id);
            if (payment == null)
            {
                return NotFound();
            }
            return PartialView(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Term")] Payment payment)
        {
            if (id != payment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("AdminProfile", "Manage", "_Payments");
            }
            return PartialView(payment);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payment = await _context.Payments
                .SingleOrDefaultAsync(m => m.Id == id);
            if (payment == null)
            {
                return NotFound();
            }

            return PartialView(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payment = await _context.Payments.SingleOrDefaultAsync(m => m.Id == id);
            _context.Payments.Remove(payment);
            await _context.SaveChangesAsync();
            return RedirectToAction("AdminProfile", "Manage", "_Payments");
        }

        private bool PaymentExists(int id)
        {
            return _context.Payments.Any(e => e.Id == id);
        }
    }
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Payments/Create.cshtml
@model OnlineCreditsTeam1.Models.Payment

@{
    ViewData["Title"] = "Create";
}



<h4>Платеж</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Тип платежа</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Term" class="control-label">Срок в месяцах</label>
                <input asp-for="Term" class="form-control" />
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default center-block">Добавить</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Список платежей</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Payments/Delete.cshtml
@model OnlineCreditsTeam1.Models.Payment

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Term)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Payments/Details.cshtml
@model OnlineCreditsTeam1.Models.Payment

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Term)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Payments/Edit.cshtml
@model OnlineCreditsTeam1.Models.Payment

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Term" class="control-label"></label>
                <input asp-for="Term" class="form-control" />
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Payments/Index.cshtml
@model IEnumerable<OnlineCreditsTeam1.Models.Payment>

@{
    ViewData["Title"] = "Index";
}

<h2>Доступные платежи</h2>

<p>
    <a class="btn tab-pane myBtn tab_btn" id="paymentsCreate" href="#_Payments"><img style="margin-right: 5px;" src="~/StaticData/Anonymous/payment.png" />Добавить новый вид платежа </a>

</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Название
                </th>
                <th>
                    Срок микрокредита
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <label>@item.Name</label>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Term)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>
<script> $("#paymentsCreate").on('click',
    function () {
        $.ajax({
            type: 'GET',
            success: $('#_Payments').load('@Url.Action("Create", "Payments")')
        });
    });</script>