OnlineCreditsTeam1/OnlineCreditsTeam1/Models/Limit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OnlineCreditsTeam1.Models
{
    public class Limit
    {
        public int Id { get; set; }
        public string LimitType { get; set; }
        public string Period { get; set; }
        public DateTime CustomLimitBeginDate { get; set; }
        public DateTime CustomLimitFinishDate { get; set; }
        [Remote(action: "ValidateMaxOrdersOnPeriod", controller: "Validation", ErrorMessage = "Количество заявок должно быть от 0 до 9999")]
        public int? MaxOrdersOnPeriod { get; set; }
        public int LimitNumberCounter { get; set; }
        [Remote(action: "ValidateMaxSumOnPeriod", controller: "Validation", ErrorMessage = "Сумма должна быть от 0 до 99999999")]
        public double? MaxSumOnPeriod{ get; set; }
        public double LimitSumCounter { get; set; }
        [Remote(action: "ValidateMaxCreditSprint", controller: "Validation", ErrorMessage = "Количество месяцев должно быть от 0 до 24")]
        public int? MaxCreditSprint { get; set; }
        public bool isActive { get; set; }
        public string Currency { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }


    }
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Controllers/LimitsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineCreditsTeam1.Data;
using OnlineCreditsTeam1.Models;
using X.PagedList;

namespace OnlineCreditsTeam1.Controllers
{
    public class LimitsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LimitsController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Limits/Details/5
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Limit limit, string begindate, string finishdate,List<string> users)
        {
            if (limit.Period == "Day")
            {
                limit.CustomLimitBeginDate = DateTime.Now;
                limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddDays(1);
            }
            else if (limit.Period == "Week")
            {
                limit.CustomLimitBeginDate = DateTime.Now;
                limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddDays(7);
            }
            else if (limit.Period == "Month")
            {
                limit.CustomLimitBeginDate = DateTime.Now;
                limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddMonths(1);
            }
            else if (limit.Period == "Year")
            {
                limit.CustomLimitBeginDate = DateTime.Now;
                limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddYears(1);
            }
            else
            {
                limit.CustomLimitBeginDate = DateTime.ParseExact(begindate, "MM/dd/yyyy", null);
                limit.CustomLimitFinishDate = DateTime.ParseExact(finishdate, "MM/dd/yyyy", null);  
            }

            if (limit.MaxCreditSprint == null) limit.MaxCreditSprint = 999999999;
            if (limit.MaxOrdersOnPeriod == null) limit.MaxOrdersOnPeriod = 999999999;
            if (limit.MaxSumOnPeriod == null) limit.MaxSumOnPeriod = 999999999;

            
            if (limit.MaxSumOnPeriod!=null)
            {
                if (!users.Contains("global") && users.Count != 0)
                {
                    foreach (string userId in users)
                    {
                        Limit l = new Limit
                        {
                            LimitNumberCounter = 0,
                            LimitSumCounter = 0,
                            Period = limit.Period,
                            CustomLimitBeginDate = limit.CustomLimitBeginDate,
                            CustomLimitFinishDate = limit.CustomLimitFinishDate,
                            MaxOrdersOnPeriod = limit.MaxOrdersOnPeriod,
                            MaxSumOnPeriod = limit.MaxSumOnPeriod,
                            MaxCreditSprint = limit.MaxCreditSprint,
                            isActive = limit.isActive,
                            Currency = limit.Currency
                        };

                        l.UserId = userId;
                        var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == userId);
                        l.User = user;
                        _context.Limit.Add(l);
                    }
                }
                else
                {
                    limit.LimitNumberCounter = 0;
                    limit.LimitSumCounter = 0;
                    _context.Limit.Add(limit);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("AdminProfile", "Manage");
            }
            return RedirectToAction("AdminProfile", "Manage");
        }

        public async Task<IActionResult> GetUsers(string keyWord)
        {
            var users = await _context.Users.Where(u => u.Role != "admin" && u.Role != "BankOperator").ToListAsync();
            if (keyWord != null)
            {  
                users = await users.Where(u =>
                    u.UserName.Contains(keyWord) ||
                    u.Role.Contains(keyWord) ||
                    u.Name.Contains(keyWord)).ToListAsync();
                return PartialView("UserSearchResult", users);
            }
            else
            {
                return PartialView("UserSearchResult", users);
            }
        }

        // GET: Limits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Dictionary<string, string> periods = new Dictionary<string, string>(5)
            {
                { "День", "Day" },
                { "Неделя", "Week" },
                { "Месяц", "Month" },
                { "Год", "Year" },
                { "Произвольный срок", "Custom" }
            };

            ViewBag.PeriodsListByCreate = periods;
            var limit = await _context.Limit.SingleOrDefaultAsync(m => m.Id == id);
            if (limit == null)
            {
                return NotFound();
            }
            return View(limit);
        }

        // POST: Limits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Limit limit, string begindate, string finishdate)
        {

            if (id != limit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (limit.Period == "Day")
                {
                    limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddDays(1);
                }
                else if (limit.Period == "Week")
                {
                    limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddDays(7);
                }
                else if (limit.Period == "Month")
                {
                    limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddMonths(1);
                }
                else if (limit.Period == "Year")
                {
                    limit.CustomLimitFinishDate = limit.CustomLimitBeginDate.AddYears(1);
                }
                else
                {
                    try
                    {
                        limit.CustomLimitBeginDate = DateTime.ParseExact(begindate, "MM/dd/yyyy", null);
                    }
                    catch (Exception e)
                    {
                        limit.CustomLimitBeginDate = DateTime.Parse(begindate);
                    }

                    try
                    {
                        limit.CustomLimitFinishDate = DateTime.ParseExact(finishdate, "MM/dd/yyyy", null);
                    }
                    catch (Exception e)

                    {
                        limit.CustomLimitFinishDate = DateTime.Parse(finishdate);
                    }    
                }
                

                if (limit.MaxCreditSprint == null) limit.MaxCreditSprint = 999999999;
                if (limit.MaxOrdersOnPeriod == null) limit.MaxOrdersOnPeriod = 999999999;
                if (limit.MaxSumOnPeriod == null) limit.MaxSumOnPeriod = 999999999;
 
                try
                {
                    _context.Update(limit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LimitExists(limit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("AdminProfile", "Manage");
            }
            return View(limit);
        }

        // GET: Limits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var limit = await _context.Limit.Include(m => m.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (limit == null)
            {
                return NotFound();
            }

            return View(limit);
        }

        // POST: Limits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var limit = await _context.Limit.Include(m => m.User).SingleOrDefaultAsync(m => m.Id == id);
            _context.Limit.Remove(limit);
            await _context.SaveChangesAsync();
            return RedirectToAction("AdminProfile", "Manage");
        }

        private bool LimitExists(int id)
        {
            return _context.Limit.Any(e => e.Id == id);
        }


        public async Task<IActionResult> GetLimits()
        {
            var limits = await _context.Limit.OrderBy(l => l.CustomLimitBeginDate).Include(l => l.User).ToListAsync();
            return PartialView("LimitsPartial",limits);
        }
        [HttpGet]
 
        public IActionResult CreateLimit()
        {
            Dictionary<string, string> periods = new Dictionary<string, string>(5)
            {
                { "День", "Day" },
                { "Неделя", "Week" },
                { "Месяц", "Month" },
                { "Год", "Year" },
                { "Произвольный срок", "Custom" }
            };
            ViewBag.PeriodsListByCreate = periods;
            var users = _context.Users.OrderByDescending(u => u.CreateTime).Where(u => u.Role!="admin" && u.Role!="BankOperator");
            ViewBag.Users = users;
            return PartialView("PartialCreateLimit");

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Limits/Delete.cshtml
@model OnlineCreditsTeam1.Models.Limit
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = "Delete";
}



<h3>@Localizer["sure_you_want_to_remove_this_limit"]</h3>
<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Localizer["user"]
        </dt>
        @if (Model.UserId == null)
        {
            <dd>
                @Localizer["all"]
            </dd>
        }
        else
        {
            <dd>
                @Html.DisplayFor(model => model.User.UserName)
            </dd>
        }

            <dt>
                @Localizer["period"]
            </dt>
        <dd>
            @Html.DisplayFor(model => model.Period)
        </dd>
        <dt>
            @Localizer["start_of_validity_limit"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomLimitBeginDate)
        </dd>
        <dt>
            @Localizer["end_of_limit"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CustomLimitFinishDate)
        </dd>
        <dt>
            @Localizer["maximum_number_of_credits_for_the_period"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxOrdersOnPeriod)
        </dd>
        <dt>
            @Localizer["the_number_of_loans_already_taken_for_the_period"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LimitNumberCounter)
        </dd>
        <dt>
            @Localizer["the_amount_of_loans_already_taken_for_the_period"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LimitSumCounter)
        </dd>
        <dt>
            @Localizer["maximum_amount_of_credits_for_the_period"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxSumOnPeriod)
        </dd>
        <dt>
            @Localizer["maximum_loan_term"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxCreditSprint)
        </dd>
        <dt>
            @Localizer["active"]
        </dt>
        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@Localizer["delete"]" class="btn btn-default" />

    </form>
</div>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Limits/Edit.cshtml
@model OnlineCreditsTeam1.Models.Limit
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["edit"];
}

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label>@Localizer["maximum_loan_term"]</label>
                @if (Model.MaxCreditSprint == 999999999)
                {
                    <input asp-for="MaxCreditSprint" type="number" class="form-control" value=@null placeholder="@Localizer["empty_field_means_unlimited"]" />
                }
                else
                {
                    <input asp-for="MaxCreditSprint" type="number" class="form-control" placeholder="@Localizer["empty_field_means_unlimited"]" />
                }

                <span asp-validation-for="MaxCreditSprint" class="text-danger"></span>
            </div>
            <input asp-for="LimitSumCounter" type="hidden" style="float:left;" readonly />
            <input asp-for="LimitNumberCounter" type="hidden" style="float:left;" readonly />
            <input asp-for="CustomLimitBeginDate" type="hidden" style="float:left;" readonly />
            <input asp-for="UserId" type="hidden" style="float:left;" readonly />
            <div class="form-group">
                <label>
                    <input asp-for="isActive" type="checkbox" style="float:left;" checked /> @Localizer["active"]
                </label>
            </div>
            <div class="form-group">
                <label>@Localizer["maximum_number_of_credits_for_the_period"]</label>
                @if (Model.MaxOrdersOnPeriod == 999999999)
                {
                    <input asp-for="MaxOrdersOnPeriod" type="number" class="form-control" value=@null placeholder="@Localizer["empty_field_means_unlimited"]" />
                }
                else
                {
                    <input asp-for="MaxOrdersOnPeriod" type="number" class="form-control" placeholder="@Localizer["empty_field_means_unlimited"]" />
                }
                <span asp-validation-for="MaxOrdersOnPeriod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@Localizer["maximum_amount_of_credits_for_the_period"]</label>
                @if (Model.MaxSumOnPeriod == 999999999)
                {
                    <input asp-for="MaxSumOnPeriod" type="number" class="form-control" value=@null placeholder="@Localizer["empty_field_means_unlimited_amount"]" />
                }
                else
                {
                    <input asp-for="MaxSumOnPeriod" type="number" class="form-control" placeholder="@Localizer["empty_field_means_unlimited_amount"]" />
                }

                <span asp-validation-for="MaxSumOnPeriod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@Localizer["period"]</label>
                <select name="Period" id="editLimitsPeriod" class="form-control">
                    @foreach (KeyValuePair<string, string> keyValue in ViewBag.PeriodsListByCreate)
                    {
                        if (keyValue.Value == Model.Period)
                        {
                            <option selected value="@keyValue.Value">@keyValue.Key</option> }
                        else
                        {
                            <option value="@keyValue.Value">@keyValue.Key</option>
                        }
                    }
                </select>
                <span asp-validation-for="Period" class="text-danger"></span>
            </div>
            @if (Model.Period == "Custom")
            {
                <div class="form-group" id="beginDate">
                    <label>@Localizer["start_of_validity_limit"]</label>
                    <input id="datepicker" name="begindate" value="@Model.CustomLimitBeginDate" class="form-control" required />
                </div>

                <div class="form-group" id="finishDate">
                    <label>@Localizer["end_of_limit"]</label>
                    <input id="datepicker1" name="finishdate" value="@Model.CustomLimitFinishDate" class="form-control" required />
                </div>
            }
            else
            {
                <div class="form-group" style='display:none;' id="beginDate">
                    <label>@Localizer["start_of_validity_limit"]</label>
                    <input id="datepicker" name="begindate" value="@Model.CustomLimitBeginDate" class="form-control" />
                </div>

                <div class="form-group" style='display:none;' id="finishDate">
                    <label>@Localizer["end_of_limit"]</label>
                    <input id="datepicker1" name="finishdate" value="@Model.CustomLimitFinishDate" class="form-control" />
                </div>
            }

            <div class="form-group">
                <input type="submit" value="@Localizer["edit"]" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    $("#datepicker").datepicker({
        inline: true,
        showOtherMonths: true,
        dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        minDate: 0,
        dateFormat: "mm/dd/yy",
        onSelect: function (dateText, inst) {
            $("input[name='begindate']").val(dateText);
        }
    }).attr('readonly', 'readonly');


    $("#datepicker1").datepicker({
        inline: true,
        showOtherMonths: true,
        dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
        minDate: 1,
        dateFormat: "mm/dd/yy",
        onSelect: function (dateText, inst) {
            $("input[name='finishdate']").val(dateText);
        }
    }).attr('readonly', 'readonly');
</script>
<script type='text/javascript'>

    $(function () {
        $('#editLimitsPeriod').on("change", function () {

            if (this.value == 'Custom') {
                $('#beginDate').show();
                $('#finishDate').show();
            }
            else {
                $('#beginDate').hide();
                $('#finishDate').hide();
            }
        });
    });
</script>



<style>

    /* DatePicker Container */
    .ui-datepicker {
        width: 216px;
        height: auto;
        margin: 5px auto 0;
        font: 9pt Arial, sans-serif;
        -webkit-box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, .5);
        -moz-box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, .5);
        box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, .5);
    }

        .ui-datepicker a {
            text-decoration: none;
        }
        /* DatePicker Table */
        .ui-datepicker table {
            width: 100%;
        }

    .ui-datepicker-header {
        background: repeat 0 0 #000;
        color: #e0e0e0;
        font-weight: bold;
        -webkit-box-shadow: inset 0px 1px 1px 0px rgba(250, 250, 250, 2);
        -moz-box-shadow: inset 0px 1px 1px 0px rgba(250, 250, 250, .2);
        box-shadow: inset 0px 1px 1px 0px rgba(250, 250, 250, .2);
        text-shadow: 1px -1px 0px #000;
        filter: dropshadow(color=#000, offx=1, offy=-1);
        line-height: 30px;
        border-width: 1px 0 0 0;
        border-style: solid;
        border-color: #111;
    }

    .ui-datepicker-title {
        text-align: center;
    }

    .ui-datepicker-prev, .ui-datepicker-next {
        display: inline-block;
        width: 30px;
        height: 30px;
        text-align: center;
        cursor: pointer;
        background-image: url('img/arrow.png');
        background-repeat: no-repeat;
        line-height: 600%;
        overflow: hidden;
    }

    .ui-datepicker-prev {
        float: left;
        background-position: center -30px;
    }

    .ui-datepicker-next {
        float: right;
        background-position: center 0px;
    }

    .ui-datepicker thead {
        background-color: #f7f7f7;
        background-image: -moz-linear-gradient(top, #f7f7f7 0%, #f1f1f1 100%);
        background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f7f7f7), color-stop(100%,#f1f1f1));
        background-image: -webkit-linear-gradient(top, #f7f7f7 0%,#f1f1f1 100%);
        background-image: -o-linear-gradient(top, #f7f7f7 0%,#f1f1f1 100%);
        background-image: -ms-linear-gradient(top, #f7f7f7 0%,#f1f1f1 100%);
        background-image: linear-gradient(top, #f7f7f7 0%,#f1f1f1 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f7f7f7', endColorstr='#f1f1f1',GradientType=0 );
        border-bottom: 1px solid #bbb;
    }

    .ui-datepicker th {
        text-transform: uppercase;
        font-size: 6pt;
        padding: 5px 0;
        color: #666666;
        text-shadow: 1px 0px 0px #fff;
        filter: dropshadow(color=#fff, offx=1, offy=0);
    }

    .ui-datepicker tbody td {
        padding: 0;
        border-right: 1px solid #bbb;
    }

        .ui-datepicker tbody td:last-child {
            border-right: 0px;
        }

    .ui-datepicker tbody tr {
        border-bottom: 1px solid #bbb;
    }

        .ui-datepicker tbody tr:last-child {
            border-bottom: 0px;
        }

    .ui-datepicker td span, .ui-datepicker td a {
        display: inline-block;
        font-weight: bold;
        text-align: center;
        width: 30px;
        height: 30px;
        line-height: 30px;
        color: #666666;
        text-shadow: 1px 1px 0px #fff;
        filter: dropshadow(color=#fff, offx=1, offy=1);
    }

    .ui-datepicker-calendar .ui-state-default {
        background: #ededed;
        background: -moz-linear-gradient(top, #ededed 0%, #dedede 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#ededed), color-stop(100%,#dedede));
        background: -webkit-linear-gradient(top, #ededed 0%,#dedede 100%);
        background: -o-linear-gradient(top, #ededed 0%,#dedede 100%);
        background: -ms-linear-gradient(top, #ededed 0%,#dedede 100%);
        background: linear-gradient(top, #ededed 0%,#dedede 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ededed', endColorstr='#dedede',GradientType=0 );
        -webkit-box-shadow: inset 1px 1px 0px 0px rgba(250, 250, 250, .5);
        -moz-box-shadow: inset 1px 1px 0px 0px rgba(250, 250, 250, .5);
        box-shadow: inset 1px 1px 0px 0px rgba(250, 250, 250, .5);
    }

    .ui-datepicker-calendar .ui-state-hover {
        background: #f7f7f7;
    }

    .ui-datepicker-calendar .ui-state-active {
        background: #6eafbf;
        -webkit-box-shadow: inset 0px 0px 10px 0px rgba(0, 0, 0, .1);
        -moz-box-shadow: inset 0px 0px 10px 0px rgba(0, 0, 0, .1);
        box-shadow: inset 0px 0px 10px 0px rgba(0, 0, 0, .1);
        color: #e0e0e0;
        text-shadow: 0px 1px 0px #4d7a85;
        filter: dropshadow(color=#4d7a85, offx=0, offy=1);
        border: 1px solid #55838f;
        position: relative;
        margin: -1px;
    }

    .ui-datepicker-unselectable .ui-state-default {
        background: #f4f4f4;
        color: #b4b3b3;
    }

    .ui-datepicker-calendar td:first-child .ui-state-active {
        width: 29px;
        margin-left: 0;
    }

    .ui-datepicker-calendar td:last-child .ui-state-active {
        width: 29px;
        margin-right: 0;
    }

    .ui-datepicker-calendar tr:last-child .ui-state-active {
        height: 29px;
        margin-bottom: 0;
    }
</style>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Limits/LimitsPartial.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model List<Limit>
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
@{
    ViewData["Title"] = "Лимиты";
}
<div id="createbutton"><button id="createLimit" class="btn btn-default" type="submit">Создать лимит</button></div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Localizer["start_of_validity_limit"]
            </th>
            <th>
                @Localizer["end_of_limit"]
            </th>
            <th>
                @Localizer["maximum_number_of_credits_for_the_period"]
            </th>
            <th>
                @Localizer["the_number_of_loans_already_taken_for_the_period"]
            </th>
            <th>
                @Localizer["maximum_amount_of_credits_for_the_period"]
            </th>
            <th>
                @Localizer["the_amount_of_loans_already_taken_for_the_period"]
            </th>
            <th>
                @Localizer["maximum_loan_term"]
            </th>
            <th>
                @Localizer["active"]
            </th>
            <th>
                @Localizer["user"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomLimitBeginDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomLimitFinishDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxOrdersOnPeriod)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LimitNumberCounter)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxSumOnPeriod)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LimitSumCounter)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxCreditSprint)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isActive)
                </td>

                @if (item.UserId == null)
                {
                <td>@Localizer["global"]</td>
                }
                else
                {
                    <td>@item.User.UserName</td>
                }

                <td>
                    <a asp-route-id="@item.Id" asp-controller="Limits" asp-action="Delete">@Localizer["delete"]</a>
                    <a asp-route-id="@item.Id" asp-controller="Limits" asp-action="Edit">@Localizer["edit"]</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $("#createLimit").click(
        function () {
            $.ajax({ type: 'GET', success: $('#_Limits').load('@Url.Action("CreateLimit", "Limits")') });
        });

</script>
@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Limits/UserSearchResult.cshtml
@model List<ApplicationUser>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<table class="table">
    <thead>
        <tr>
            <th>
                @Localizer["name"]
            </th>
            <th>
                @Localizer["number"]
            </th>
            <th>
                @Localizer["role"]
            </th>
            <th>
                @Localizer["choose"]
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="3">@Localizer["global"]</td>
            <td>
                <label>
                    <input type="checkbox" />
                    <span class="pcheckbox"> </span>
                </label>
            </td>
        </tr>
        @foreach (ApplicationUser user in Model)
        {
            <tr>
                <td>
                    @user.Name
                </td>
                <td>
                    @user.UserName
                </td>
                <td>
                    @user.Role
                </td>
                <td>
                    <label>
                        <input type="checkbox" name="users" value="@user.Id" />
                        <span class="pcheckbox"> </span>
                    </label>
                </td>
            </tr>
        }
    </tbody>
</table>