OnlineCreditsTeam1/OnlineCreditsTeam1/Models/Provider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineCreditsTeam1.Models
{
    public class Provider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PaymentId { get; set; }
        public Payment Payment { get; set; }
    }
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineCreditsTeam1.Data;
using OnlineCreditsTeam1.Models;

namespace OnlineCreditsTeam1.Controllers
{
    public class ProvidersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProvidersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Providers
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Providers.Include(p => p.Payment);
            return PartialView(await applicationDbContext.ToListAsync());
        }

        // GET: Providers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers
                .Include(p => p.Payment)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (provider == null)
            {
                return NotFound();
            }

            return PartialView(provider);
        }

        // GET: Providers/Create
        public IActionResult Create()
        {
            ViewData["PaymentId"] = new SelectList(_context.Payments, "Id", "Name");
            return PartialView();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PaymentId")] Provider provider)
        {
            if (ModelState.IsValid)
            {
                _context.Add(provider);
                await _context.SaveChangesAsync();
                return RedirectToAction("AdminProfile", "Manage", "_Providers");
            }
            ViewData["PaymentId"] = new SelectList(_context.Payments, "Id", "Name", provider.PaymentId);
            return PartialView(provider);
        }

        // GET: Providers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers.SingleOrDefaultAsync(m => m.Id == id);
            if (provider == null)
            {
                return NotFound();
            }
            ViewData["PaymentId"] = new SelectList(_context.Payments, "Id", "Id", provider.PaymentId);
            return PartialView(provider);
        }

        // POST: Providers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,PaymentId")] Provider provider)
        {
            if (id != provider.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(provider);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProviderExists(provider.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("AdminProfile", "Manage", "_Providers");
            }
            ViewData["PaymentId"] = new SelectList(_context.Payments, "Id", "Id", provider.PaymentId);
            return PartialView(provider);
        }

        // GET: Providers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers
                .Include(p => p.Payment)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (provider == null)
            {
                return NotFound();
            }

            return PartialView(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var provider = await _context.Providers.SingleOrDefaultAsync(m => m.Id == id);
            _context.Providers.Remove(provider);
            await _context.SaveChangesAsync();
            return RedirectToAction("AdminProfile", "Manage", "_Providers");
        }

        private bool ProviderExists(int id)
        {
            return _context.Providers.Any(e => e.Id == id);
        }
    }
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Providers/Create.cshtml
@model OnlineCreditsTeam1.Models.Provider

@{
    ViewData["Title"] = "Create";
}



<h4>Провайдер</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentId" class="control-label">Тип платежа</label>
                <select asp-for="PaymentId" class ="form-control" asp-items="ViewBag.PaymentId"></select>
            </div>
            <div class="form-group">
                
                <button type="submit" class="btn btn-default center-block">Добавить</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Список провайдеров</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Providers/Delete.cshtml
@model OnlineCreditsTeam1.Models.Provider

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Provider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Payment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Payment.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Providers/Details.cshtml
@model OnlineCreditsTeam1.Models.Provider

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Provider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Payment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Payment.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Providers/Edit.cshtml
@model OnlineCreditsTeam1.Models.Provider

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Provider</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentId" class="control-label"></label>
                <select asp-for="PaymentId" class="form-control" asp-items="ViewBag.PaymentId"></select>
                <span asp-validation-for="PaymentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OnlineCreditsTeam1/OnlineCreditsTeam1/Views/Providers/Index.cshtml
@model IEnumerable<OnlineCreditsTeam1.Models.Provider>

@{
    ViewData["Title"] = "Index";
}

<h2>Доступные провайдеры</h2>

<p>
    <a class="btn tab-pane myBtn tab_btn" id="providersCreate" href="#_Providers"><img style="margin-right: 5px;" src="~/StaticData/Anonymous/Provider.png" />Добавить провайдера </a>
    
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Провайдеры
                </th>
            <th>
                Виды платежей
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Payment.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Изменить платеж</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>
<script>$("#providersCreate").on('click',
    function () {
        $.ajax({
            type: 'GET',
            success: $('#_Providers').load('@Url.Action("Create", "Providers")')
        });
    });</script>